# viewer-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer
  annotations:
    rbac.authorization.kubernetes.io/description: "Read-only доступ ко всем ресурсам (кроме Secrets)"
rules:
- apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io"]
  resources: 
    - pods
    - deployments
    - services
    - configmaps
    - namespaces
    - ingresses
    - jobs
    - cronjobs
    - replicasets
    - statefulsets
    - daemonsets
    - persistentvolumes
    - persistentvolumeclaims
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]